services:

  #apigateway
  apigateway-backend:
    build:
      context: apigateway/.
      dockerfile: Dockerfile
    ports:
      - "7000:8080"
      - "80:8080"

  #userservice
  userservice-backend:
    hostname: userservice-backend
    build:
      context: userservice/.
      dockerfile: Dockerfile

    ports:
      - "7001:8080"

  userservice-database:
    hostname: userservice-database
    image: postgres:16
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: db
    ports:
      - "6001:5432"
    volumes:
      - ./userservice/db:/var/lib/postgresql/data
