@startuml

entity "Reactions" {
  * id : NUMBER
  --
  reaction_name: VARCHAR
  owner_id : NUMBER
  file: BYTE
  created_at: TIMESTAMP
}


entity "ReactionStatistic" {
  * post_id : NUMBER
  * user_id : NUMBER
  * reaction_id : NUMBER
  --
  reacted_at: TIMESTAMP
  moon_phase: VARCHAR
}

entity "ViewStatistic" {
  * post_id : NUMBER
  * user_id : NUMBER
  --
  viewed_at: TIMESTAMP
  moon_phase: VARCHAR
  dice_100_roll: NUMBER
}

Reactions --{ ReactionStatistic

@enduml