@startuml

entity "User" {
  * id : NUMBER
  --
  name : VARCHAR
  surname : VARCHAR
  login : VARCHAR
  password : VARCHAR
}

entity "Role" {
  * id : NUMBER
  --
  name : VARCHAR
  description: VARCHAR
  rights: JSON
  parent: NUMBER
}

entity "UserRole" {
  * user_id : NUMBER
  * role_id : NUMBER
}

User --{ UserRole
Role --{ UserRole

@enduml