@startuml

entity "User" {
  * id: UUIDv7
  --
  name: VARCHAR
  surname: VARCHAR
  dob: DATE
  email: VARCHAR
  phone: VARCHAR
  login: VARCHAR
  password: VARCHAR
  created_at: TIMESTAMP
  edited_at: TIMESTAMP
}

entity "Role" {
  * id : NUMBER
  --
  name : VARCHAR
  description: VARCHAR
  rights: JSON
  parent: NUMBER
}

entity "UserRole" {
  * user_id : NUMBER
  * role_id : NUMBER
}

User --{ UserRole
Role --{ UserRole

@enduml